# This file defines a Kubernetes service for the sample ecommerce Node.js application.
# It exposes the application to the outside world and allows it to be accessed via a LoadBalancer.

apiVersion: v1
kind: Service
metadata:
  name: sample-ecommerce-nodejs-app-service
  labels:
    apps: myapps
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    apps: myapps